squawker-django/squawker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('squawker_app.urls')),
    url(r'^admin/', admin.site.urls)
]

squawker-django/squawker_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'squawker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add_squawker, name='add'),
]

squawker-django/squawker_app/models.py
from django.db import models


class Squawks(models.Model):
    squawk = models.CharField(max_length=140)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.squawk

squawker-django/squawker_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse
from django.views.generic import RedirectView
from .models import Squawks


def index(request):
    context = {'past_squawks': Squawks.objects.order_by('-id')}
    return render(request, 'index.html', context)


def add_squawker(request):
    q = Squawks(squawk=request.POST['content'])
    if len(q.squawk) > 140:
        response = HttpResponse('Please enter less than 140 characters')
        response.status_code = 400
        return response
    q.save()
    return index(request)

squawker-django/squawker_app/templates/index.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>Squawker</title>
    </head>
    
    <body>
        <h1>Squawker!</h1>
        <form action="{% url 'squawker:add'%}" method="post">
            {% csrf_token %}
            <textarea name="content" maxlength="140" placeholder="Say something..."></textarea>
            <input type="submit">
            <h2>Your squawks</h2>
            {% for s in past_squawks %}
            <p>{{s.squawk}}</p>
            {% endfor %}
        </form>
    </body>
</html>